### ISSUE TITLE
JSF resources outbound URL rewriting

### ISSUE THREAD

**Issue by beikov** [ocpsoft/rewrite#182]
The URLs of JSF resources that are rendered via h:outputStylesheet and h:outputScript do not get outbound rewritten.

**Comment by beikov** [comment]
I just saw this issue again and it got me thinking. Why not do this magic translation @chkal mentioned in the Join class? When the path contains a question mark it would just translate to the rule described above. Less confusion for people but still a nice feature making it more pleasent to use :)

**Comment by chkal** [comment]
What do you mean with "magic translation"? ;)
