### ISSUE TITLE
Evaluation of conditions 'And' and 'Or'

### ISSUE THREAD

**Issue by lathil** [ocpsoft/rewrite#185]
I am trying using Rewrite in a JSF 2 application. My rule look like this:

``` java
.addRule()
.when(Direction.isInbound()
    .and(Path.matches(fromPath.substring(fromPath.indexOf(contextPath) > -1 ? contextPath.length(): 0, fromPath.length()))
    .and(Domain.matches(from.getHost()))
    .and(ServerPort.is(from.getPort()))))
.perform(Log.message(Level.INFO, "redirect from: " + redirectFromTo[0] +  " to: " + redirectFromTo[1])
    .and(Redirect.permanent(redirectFromTo[1])));
```

Problem is, all the conditions are evaluated even if the first is false. In the case of an inbound, it's no probleme, but in the case of an outbound, the server port might be null as JSF might be filling resources url ( relatives ) in it page.

Wouldn't be better to have a break in the evaluate method of And and Or classes like this:

``` java
 public boolean evaluate(final Rewrite event, final EvaluationContext context)
   {
      boolean result = true;
      for (int i = 0; i < conditions.length; i++) {
         if (!conditions[i].evaluate(event, context))
         {
            result = false;
            break;

         }
      }
      return result;
   }
```

**Comment by lincolnthree** [comment]
The other option to avoid evaluating all of a condition is to wrap the condition in a Subset. See: https://github.com/ocpsoft/rewrite/blob/master/api/src/main/java/org/ocpsoft/rewrite/config/Subset.java

**Comment by lincolnthree** [comment]
Closed as out of date.
