### ISSUE TITLE
DefaultActionUrlProvider breaks JSF error pages containing forms

### ISSUE THREAD

**Issue by DonatasC** [ocpsoft/rewrite#190]
org.ocpsoft.rewrite.faces.DefaultActionUrlProvider returns incorrect form action URLs in the case error page was rendered.

To reproduce:
1. Create error page (error.jsf) containing h:form (and optionally submit button)
2. Register the error page in web.xml:
```
    <error-page>
        <error-code>404</error-code>
        <location>/error.jsf</location>
    </error-page>
```
or just (to be the default error page):
```
   <error-page>
        <location>/error.jsf</location>
   </error-page>
```
3. No special rewrite rules are needed - the bug can be reproduced just by including:
rewrite-servlet and rewrite-integration-faces (version 2.0.12.Final or 3.0.0Alpha4)
4. Point the browser to some non-existing page, e.g.: http://host:port/context/nonExisting.jsf
5. error.jsf gets rendered; view page source in browser and observe, that all h:form contain action URL: http://host:port/context/nonExisting.jsf
6. Press any submit button (that submits JSF form) - JSF implementation fails badly (in my case MyFaces 2.2.6).

The real problem is org.ocpsoft.rewrite.faces.DefaultActionUrlProvider:
```
   public String getActionURL(FacesContext context, String viewId)
   {
      HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
      return FacesRewriteLifecycleListener.getOriginalRequestURL(request);
   }
```
I would say this is dangerous at least - your code doesn't even check whether viewId is being mentioned in FacesRewriteLifecycleListener.getOriginalRequestURL(request) at all.

Workarround: I have created and registered in SPI this class (it delegates getActionURL() back to JSF implementation, in this case MyFaces):
```
public class RewriteActionUrlProvider implements FacesActionUrlProvider {
    @Override
    public String getActionURL(FacesContext context, String viewId)
    {
        return new DefaultViewHandlerSupport(context).calculateActionURL(context, viewId);
    }

    @Override
    public int priority()
    {
        return -1;
    }
}
```
Well, priority ordering is strange too :) I would assume, that provider with higher priority would win, it is vice-versa actually.

**Comment by lincolnthree** [comment]
I think that is probably a good solution.

**Comment by chkal** [comment]
I think this should go directly into DefaultActionUrlProvider. 

Unfortunately it isn't straight forward to obtain the dispatch type. HttpServletRequest.getDispatchType() was introduced in Servlet 3.0 and we currently still support Servlet 2.5. We have an SPI called DispatcherTypeProvider with an implementation for Servlet 2.5 that basically uses some hacks to determine the dispatch type. However, if I remember correctly these hacks doesn't work with dispatch type ERROR. See:

https://github.com/ocpsoft/rewrite/blob/master/impl-servlet-2.5/src/main/java/org/ocpsoft/rewrite/servlet/impl/Servlet25DispatcherTypeProvider.java#L40-50

But perhaps we can ignore Servlet 2.5 here? We could add something like this to DefaultActionUrlProvider:

```java
public String getActionURL(FacesContext context, String viewId) {
    DispatcherType type = .... // use DispatcherTypeProvider to get the type
    if(type == null || type != DispatcherType.ERROR) {
        return ... // current implementation
    }
    return null;
}
```

This should work, correct?

**Comment by lincolnthree** [comment]
I think we can identify the error scenario in servlet 2.5 using the following check:

```

   @Override
   public DispatcherType getDispatcherType(ServletRequest request, ServletContext context)
   {
      if (request.getAttribute("javax.servlet.forward.request_uri") != null) {
         return DispatcherType.FORWARD;
      }

      if (request.getAttribute("javax.servlet.include.request_uri") != null) {
         return DispatcherType.INCLUDE;
      }

      Throwable throwable = (Throwable) request.getAttribute("javax.servlet.error.exception");
      if (throwable != null) {
         return DispatcherType.ERROR;
      }

      return DispatcherType.REQUEST;

   }
```

**Comment by lincolnthree** [comment]
I think I have a solution for this, but I'm not really sure how to write a test case. I'm going to check in the solution then maybe we can come up with a test for it :p I know that's backwards, but I don't have much time right now.

**Comment by lincolnthree** [comment]
Tests are passing, just need a new test for this feature.

**Comment by chkal** [comment]
@lincolnthree: Yeah, this should work to detect the error dispatch type in Servlet 2.5... Great idea! :)

**Comment by lincolnthree** [comment]
I believe this issue is resolved. Please reopen if it does not work. Check the 3.0.0.Alpha10 release.
