### ISSUE TITLE
404 error handling breaks when Rewrite is enabled

### ISSUE THREAD

**Issue by elcodedocle** [ocpsoft/rewrite#198]
This could be related to #100 

My web.xml:

	<error-page>
		<error-code>404</error-code>
		<location>/404.xhtml</location>
	</error-page>

On my bean, I send a 404 if the requested content is not in the database:
 
    FacesContext facesContext = FacesContext.getCurrentInstance();
    facesContext.getExternalContext().responseSendError(404, "Not found.");
    facesContext.responseComplete();

After adding Rewrite as a dependency to my pom (2.0.12.Final) I stil get the correct 404 response code, but the response page defined in web.xml (404.xhtml) is not loaded (no errors on the log, but no content).

I am using tomcat 7 with servlet api 3, so no further changes are required to deploy Rewrite. This problem happens whether or not I implement a ConfigurationProvider, like the one I've tried, which seems to be working fine appart from this problem:

    @RewriteConfiguration
    public class RewriteConfigurationProvider extends HttpConfigurationProvider {
    	@Override
    	public int priority() {
    		return 10;
    	}
    	@Override
    	public Configuration getConfiguration(final ServletContext context) {
    		return ConfigurationBuilder.begin()
    				.addRule( Join.path("/public/dynamic/{webpath}").to("/public/dynamic/dynamic.xhtml") ).where("webpath").matches(".*");
       }
    }

I'm not sure if this is a bug or misconfiguration. The manual page has been eaten by sharks, and I couldn't find info on how to return to the original behavior on the configuration guide...

**Comment by elcodedocle** [comment]
(forget about it, it was a misconfiguration error, not even related to rewrite)

**Comment by lincolnthree** [comment]
Thanks for updating your issue! Glad you figured out the problem :)

On Thu, Jan 15, 2015 at 10:58 AM, Gael Abadin <notifications@github.com>
wrote:

> Closed #198 <https://github.com/ocpsoft/rewrite/issues/198>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/rewrite/issues/198#event-219490113>.
>



-- 
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."
