### ISSUE TITLE
Unable to create a rule if directory with the same name exists

### ISSUE THREAD

**Issue by edvin** [ocpsoft/rewrite#200]
I want to make `/controlpanel/login/login.xhtm`l available at `/controlpanel/login`, so I've added the following rule:

`Join.path("/controlpanel/login").to("/controlpanel/login/login.xhtml")`

This doesn't work, seemingly because the directory `/controlpanel/login` exists. The rule works if I change the Join.path to `/controlpanel/login/x`, though. RFE: Rules should take precedence over directories.

rewrite-servlet and rewrite-integration-faces 2.0.12.Final, Wildfly 8.2.0.Final

**Comment by chkal** [comment]
This is not an Rewrite issue. This is a requirement of the Servlet spec. If there is a directory `/foobar` in the WAR archive and a request for `/foobar` is received, the request must be redirected to `/foobar/`.

Have a look at section 10.10 of the Servlet 3.1 spec.

I also had such problems in the past. AFAIK there is nothing you can do about it. :(

**Comment by edvin** [comment]
Thanks for the quick reply and the reference @chkal :)
