### ISSUE TITLE
org.ocpsoft.rewrite.servlet.util.URLBuilder - private String decodeSegment(final String segment)

### ISSUE THREAD

**Issue by michelepra** [ocpsoft/rewrite#203]
http://www.w3schools.com/tags/ref_urlencode.asp

String prepared = ("http://localhost/" + segment).replaceAll("\\+", "%20");

the '+' must be replaced with "%2B"

please fix soon this bug.

Thanks

**Comment by chkal** [comment]
Thanks. Good catch. Not sure why this was added to the code. The class is deprecated anyway and we should get rid of it. ;)

**Comment by michelepra** [comment]
Yes but it's currently used in last final release 2.0.12
Let me be crazy this morning to solve this problem.
The only workaround is to clone Join rule that use a clone version of Path condition that don't use URLBuilder internally, horrible but it work :)

Thank you for this fast solution
