### ISSUE TITLE
Unsupported FacesConverterProvider#getByConverterType

### ISSUE THREAD

**Issue by dabloem** [ocpsoft/rewrite#205]
implement getByConverterType in order to use a FacesConverter with the 'with' attribute of @Convert

**Comment by chkal** [comment]
As far as I know JSF doesn't provide such an API. I think that was the reason why getByConverterType isn't implemented.

**Comment by dabloem** [comment]
could you take a look at my proposal https://gist.github.com/dabloem/a408c4623efd6d8b7223 ?

**Comment by dabloem** [comment]
I think this issue can be closed. I see now within the tests, there is already a test for getByType, which uses the targetType. (I am just wondering why it didn't work the first time I used @Convert)

**Comment by chkal** [comment]
Okay. Feel free to reopen the issue if it doesn't work as expected.
