### ISSUE TITLE
Using named parameters on transient view gives warnings

### ISSUE THREAD

**Issue by kalgon** [ocpsoft/rewrite#208]
Using a transient view (without any bean) and named parameters (`/documents/#{id}`) gives the following warning: @ViewScoped beans are not supported on stateless views.

I suspect rewrite to store some information in the viewscope (even when using transient views).

[stackoverflow reference](http://stackoverflow.com/questions/30375283/prettyfaces-transient-view-and-named-path-parameters-give-a-warning)

**Comment by chkal** [comment]
Rewrite doesn't store anything in view scope. Does it also happen if you use EL style parameter injection:

    <pattern value="/document/#{someBean.id}" />

**Comment by kalgon** [comment]
Binding the parameter directly on a bean does not raise the warning.

**Comment by kalgon** [comment]
I'm not a JSF expert but could this warning come from calling `UIViewRoot.getViewMap()` instead of `UIViewRoot.getViewMap(false)` ?

**Comment by chkal** [comment]
Possible, but AFAIK Rewrite doesn't do anything like that.

**Comment by kalgon** [comment]
`UIViewRoot.getViewMap(true)` is called (indirectly) from `FacesElUtils`.

    UIViewRoot.getViewMap(boolean) line: 1551
    UIViewRoot.getViewMap() line: 1502
    ScopedAttributeELResolver.setValue(ELContext, Object, Object, Object) line: 166
    DemuxCompositeELResolver._setValue(int, ELResolver[], ELContext, Object, Object, Object) line: 255
    DemuxCompositeELResolver.setValue(ELContext, Object, Object, Object) line: 281
    AstIdentifier.setValue(EvaluationContext, Object) line: 169
    ValueExpressionImpl.setValue(ELContext, Object) line: 294
    WeldValueExpression.setValue(ELContext, Object) line: 64
    WeldValueExpression.setValue(ELContext, Object) line: 64
    FacesElUtils.setValue(FacesContext, String, Object) line: 86
    ParameterInjector.injectPathParams(FacesContext, URL, UrlMapping) line: 90
    ParameterInjector.injectParameters(FacesContext) line: 54
    PrettyPhaseListener.afterPhase(PhaseEvent) line: 102

**Comment by kalgon** [comment]
It could be a bug in `com.sun.faces.el.ScopedAttributeELResolver.setValue()`: nothing is done to check if the ViewRoot is transient or not and `getViewMap()` is called.

**Comment by chkal** [comment]
I agree. Rewrite does not explicitly store anything in the view map. For backwards compatibility it just stores the path parameter via EL in `#{name}`. Actually this isn't necessary, because Rewrite should actually just turn the parameter into a query parameter. But we decided to keep it that way for backwards compatibility.

**Comment by kalgon** [comment]
Ok, thanks. I opened a [mojarra issue](https://java.net/jira/browse/JAVASERVERFACES-3939). I hope it won't take too long to fix...

In the meantime and if that is not too much to ask, do you think it could be possible to prevent Rewrite to store useless parameters via some kind of configuration flags? I know the problem is not on your side but you may react more quickly than the JSF implementation.

**Comment by chkal** [comment]
To be honest, I'm not sure if such an configuration options makes sense as this is valid behavior. And I think this could also break something like:

    <pattern value="/foo/#{someBean.param}" />

However, if you find some way to implement this flag without breaking something, a pull request would be awesome.

**Comment by kalgon** [comment]
In the meantime, I am using `/documents/#{id : requestScope.id}`

**Comment by kalgon** [comment]
Closing as this issue is a [mojarra-specific problem](https://github.com/eclipse-ee4j/mojarra/issues/3943).
