### ISSUE TITLE
URLBuilder.decodeSegment / DefaultHttpRewriteProvider.rewriteHttp taking much CPU time?

### ISSUE THREAD

**Issue by ceefour** [ocpsoft/rewrite#213]
I was surprised when I see this in Java Mission Control (see attachment)

![download_20150622_133802](https://cloud.githubusercontent.com/assets/24123/8276803/d45ca766-18e4-11e5-96fb-8740dfab4bd9.png)
Cc @rudiw

**Comment by ceefour** [comment]
Also with `org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.rewriteHttp(HttpServletRewrite)`

![selection_112](https://cloud.githubusercontent.com/assets/24123/8285978/147b948c-1931-11e5-9b71-a1275421ac6c.png)

**Comment by chkal** [comment]
Hmmm. AFAIK URLBuilder is deprecated. It still uses java.net.URI for URL decoding. I already reimplemented the decoding in AdressBuilder. Actually we should get rid of URLBuilder in favor of AddressBuilder. But IIRC there were some test failures the last time I tried to remove it.

**Comment by lincolnthree** [comment]
Yes, we need to do that, or at least replace the encoding with the encoding provider that AddressBuilder uses.
