### ISSUE TITLE
Duplicate parameters added to ServletRequest parameterMap

### ISSUE THREAD

**Issue by seanf** [ocpsoft/rewrite#223]
When using just this rule:

```
@RewriteConfiguration
public class UrlRewriteConfig extends HttpConfigurationProvider {

    @Override
    public Configuration getConfiguration(final ServletContext context) {
        return ConfigurationBuilder.begin()
                .addRule(Join.path("/project/view/{slug}").to("/project/project.xhtml"))
                ;
    }

    @Override
    public int priority() {
        return 0;
    }
}
```

I found that requests to `/project/view/foo` had four copies of the parameter `slug`, when accessed via `ServletRequest.getParameterMap()` or `getParameterValues()`. From my debugging, it appears that the `slug` binding is being registered repeatedly during filter initialisation at startup. (`ParameterBuilder.bindsTo` appears to be called too many times during `ConditionVisit.accept` and/or `OperationVisit.accept`)

Tested using Rewrite 3.0.0.Alpha10 and Alpha1.

So far the only workaround I have is to install another servlet filter which blindly strips out any duplicated parameters, which will no doubt come back to bite me.

**Comment by chkal** [comment]
Thanks for reporting this.

Unfortunately I'm currently very busy and therefore don't find much time to work on Rewrite. :disappointed:

Perhaps you could ask @lincolnthree if he finds some time to help a fellow worker. :)

**Comment by lincolnthree** [comment]
I've tried (finally) to take a look at this issue, but I have been unable to reproduce it. Do you think you could try this in a sample application? I'm guessing there is some other custom functionality that is causing this (not Rewrite), but those may be famous last words, of course.

There is a chance we are causing this in your specific scenario, but without more information it will be hard to diagnose. Any chance you could upload a sample application or instructions on how to reproduce this?

Thanks.

**Comment by seanf** [comment]
Hi @lincolnthree, thanks for looking into it. This project can be used to reproduce it: https://github.com/seanf/wildfly-quickstart/tree/rewrite-issue-223/helloworld

As described in the README, you'll need WildFly 10 running; then you can deploy with `mvn clean install wildfly:deploy`.

Then visit [http://localhost:8080/wildfly-helloworld/hello/world](http://localhost:8080/wildfly-helloworld/hello/world). `/hello/world` should be rewritten to `/HelloWorld?path=world` but the `path` value `world` actually appears in the parameter map four times, like this:

    ParameterMap:
    path: [world, world, world, world]

**Comment by csyperski** [comment]
Is this bug still present, I just updated from the 2.x branch to 2.x and I'm seeing the exact same thing where each of my params are being populated 4 times?  

`.addRule(Join.path("/c/{c}").to("/customer?c={c}"))`

Results in the value for c being something like [ 2, 2, 2, 2 ]

**Comment by didiez** [comment]
It seems that the bug was introduced here  https://github.com/ocpsoft/rewrite/commit/6f8000#diff-524e12f568e84bf1f7013a8ba86c796a

There has been a few commits and refactorings after that, so I'm not sure whether we can simply add back again the condition or there is a better way to solve this.
