### ISSUE TITLE
Extend ByteCodeFilter to Java 8

### ISSUE THREAD

**Issue by Tires** [ocpsoft/rewrite#229]
Three new constants will enable Java 8 support:

   private static final int CONSTANT_MethodHandle = 15;
   private static final int CONSTANT_MethodType = 16;
   private static final int CONSTANT_InvokeDynamic = 18;

Implementation can be:

         case CONSTANT_MethodHandle:
           /*
            * CONSTANT_MethodHandle_info {
            *     u1 tag;
            *     u1 reference_kind;
            *     u2 reference_index;
            * }
            */
           in.readByte();
           in.readShort();
           break;
           
         case CONSTANT_MethodType:
           /*
            * CONSTANT_MethodType_info {
            *     u1 tag;
            *     u2 descriptor_index;
            * }
            */
           in.readShort();
           break;
           
         case CONSTANT_InvokeDynamic:
           /*
            * CONSTANT_InvokeDynamic_info {
            *     u1 tag;
            *     u2 bootstrap_method_attr_index;
            *     u2 name_and_type_index;
            * }
            */
           in.readShort();
           in.readShort();
           break;

Please verify correctness.

**Comment by chkal** [comment]
Awesome. Thanks a lot. Could you perhaps open a pull request for that?

**Comment by Tires** [comment]
I'm not so familiar with GIT, I'll ask somebody to assist with that.

**Comment by chkal** [comment]
Awesome!

**Comment by chkal** [comment]
Fixed with #230
