### ISSUE TITLE
URLMapping annotation supports regular expressions?

### ISSUE THREAD

**Issue by tiago156** [ocpsoft/rewrite#232]
Is this code supposed to work?

```
@Named("bean")
@RequestScoped
@URLMapping(id = "store", pattern = "/store/#{ /[a-z]+/ bean.id }", viewId = "/faces/shop/store.jsf")
public class StoreBean {
  /* your code */
}
```

Thanks!

**Comment by chkal** [comment]
Yes, it should work.

**Comment by tiago156** [comment]
Sorry, on the original post the regex was wrong, I can't make it work with the regex `\d+`.

Is this tag correct `#{ /\\d+/ bean.id }`?

On the code below the method `check` is never called using the url `http://localhost:8080/store/123`

```
@Named("bean")
@RequestScoped
@URLMapping(id = "store", pattern = "/store/#{ /\\d+/ bean.id }", viewId = "/faces/shop/store.jsf")
public class StoreBean {
    private long id;

    public long getId() { return id; }
    public void setId(long id) { this.id = id; }

    @URLAction
    public String check() {
        System.out.println(id);
        return null;
    }
}
```

Thanks.

**Comment by chkal** [comment]
If I remember correctly, you actually have to use:

    #{ /\\\\d+/ bean.id }

I know, this is ugly. But the core of PrettyFaces requires `\\d` and so your have to escape both `\` characters in a Java string literal. That's a known issue with PrettyFaces. But it is something we cannot change to preserve backwards compatibility.

**Comment by tiago156** [comment]
Worked! Thank you, and congrats for the awesome job on this framework.

Cheers.

**Comment by chkal** [comment]
Thanks! You're welcome! :beers:
