### ISSUE TITLE
Lookup rule resolution

### ISSUE THREAD

**Issue by mrginglymus** [ocpsoft/rewrite#233]
Hi all,

We're using rewrite as a fairly simple clean url provider; all our rules are of the form Join.path().to(), with a few URL parameters.

However, we've encountered a few places (messages, emails, plus a couple of others) where we haven't been able to leverage the automatic rewriting capabilities. We are trying to keep all of our clean URLs in one place, so want to avoid hard-coding clean urls outside of the configuration file.

Is there an easy way to pass in a url ("/pages/admin/people/person.xhtml?personId=3") and get back the clean URL ("/admin/people/3/"), so that we can use in something like an email.

Cheers.

**Comment by chkal** [comment]
The simplest way to achieve this is to use `HttpServletResponse.encodeURL()` for this. This basically the hook used by Rewrite to do all of the outbound rewriting. Some try something like this:

```java
String prettyUrl = response.encodeURL( uglyUrl );
```

**Comment by mrginglymus** [comment]
Thanks, that works great within the request/response cycle...however! Our emails are sent on a JMS queue, so we don't have a live response to plug into. Is there a way I can get around this for my asynchronous URL needs?

Thanks again!

**Comment by chkal** [comment]
To be honest, I don't think this is possible. Rewrite requires some more context which is only available in the web application Rewrite is deployed to.

However, you could have a look how Rewrite triggers the outbound rewriting for `HttpServletResponse.encodeUrl()`:

https://github.com/ocpsoft/rewrite/blob/master/impl-servlet/src/main/java/org/ocpsoft/rewrite/servlet/impl/HttpRewriteWrappedResponse.java#L392

**Comment by lincolnthree** [comment]
Just a thought on this. You might be able to get this to work if you mocked the HttpServletRequest and HttpServletResponse.

I'd actually be interested in seeing a patch that makes it possible to use Rewrite in an "offline" context. Assuming the design was good, I'd be willing to entertain making that a feature.

**Comment by mrginglymus** [comment]
Thanks, I'll have a play.
