### ISSUE TITLE
3.4.0.FINAL rewrite-servlet includes all javax servlet specification

### ISSUE THREAD

**Issue by cocorossello** [ocpsoft/rewrite#241]
The jar file includes all specification classes, resulting in conflicts when deploying in a server (TomEE 7.0.1 in my case).

Should we use another dependency since 3.4.0 or is it a mistake?

**Comment by chkal** [comment]
Thanks for pointing this out. That's actually a mistake. Not sure why this happend. But packaging Java EE API classes is definitely not correct. Looks like some problem with the shade plugin. I'll have a look at this ASAP.

**Comment by chkal** [comment]
Hey. I spent some time to fix the release process and prepared the 3.4.1.Final release. Could you perhaps give it a try before I release it? The release is staged in this repository:

https://oss.sonatype.org/content/repositories/orgocpsoft-1058

You can basically add the repository to your pom and update the version to 3.4.1.Final. If everything works fine it is just a single button click for me to release this version to Maven central.

Thanks a lot.

**Comment by cocorossello** [comment]
Hi,

It is working now, altough I'm not getting the rewritten URL for some reason. I'll investigate a little bit to see if it's my application...

Thank you!

**Comment by cocorossello** [comment]
Indeed, it was a problem of mine. The project is working fine. 

Thanks

**Comment by chkal** [comment]
Awesome! Thanks for giving the staged version a try.

I'll push out the release later today or tomorrow. The exact same JARs will be published to Maven central. So there is nothing for you to do beside removing the staging repository from your pom.

**Comment by rudiw** [comment]
Tag @ceefour

**Comment by rudiw** [comment]
@chkal Thank you! Very much waiting for this fix!
