### ISSUE TITLE
OCPSoft Rewrite memory usage too much

### ISSUE THREAD

**Issue by rudiw** [ocpsoft/rewrite#242]
Version: 2.0.12.Final

![image](https://cloud.githubusercontent.com/assets/1597815/17849005/ae70a396-6824-11e6-9221-fa6b2400ec85.png)

Compare the above ocpsoft rewrite usage (~ 2 GB!) with Wicket + our own class `id.co.bippo.web.pub.BippoPubPage` (~146 MB) :

![image](https://cloud.githubusercontent.com/assets/1597815/17849113/475da310-6825-11e6-9175-6b327f25b6f0.png)

Related to #213 
Tag @ceefour

**Comment by lincolnthree** [comment]
Hi! Thanks for reporting this. We've seen some other performance issues with the URLBuilder, and we made some adjustments in the 3.4.1.Final release that were intended to address these:

https://github.com/ocpsoft/rewrite/commit/3a6546e5ca01c726c8a0630b495ef52856cc72be

However, there was a packaging issue with 3.4.1.Final, so we are working on releasing 3.4.2.Final ASAP.

Feel free to try 3.4.1.Final to see if it resolves this performance issue, but we recommend upgrading to 3.4.2.Final as soon as it is released.

**Comment by lincolnthree** [comment]
Additionally, you can try 3.4.1.Final in staging now by adding the following repository to your `pom.xml`

https://oss.sonatype.org/content/repositories/orgocpsoft-1058

**Comment by lincolnthree** [comment]
Actually, 3.4.1.Final has been released. You should be able to upgrade now.

**Comment by lincolnthree** [comment]
Closed as out-of-date.
