### ISSUE TITLE
I can after the response has been committed call sendRedirect() ?

### ISSUE THREAD

**Issue by zhanwen** [ocpsoft/rewrite#249]
public void test(HttpServletResponse response) throws Exception {　　
　　　　//response commit　　
　　　　//then i want redirect　　

}

**Comment by chkal** [comment]
No, that's a restriction of the Servlet API. If you commit the response, the response headers are sent to the client and therefore you cannot change them after that.

**Comment by zhanwen** [comment]
Thanks for you response. I will select other way deal.
