### ISSUE TITLE
Java class-less rewriting?

### ISSUE THREAD

**Issue by Quix0r** [ocpsoft/rewrite#251]
Hi,

with pretty-faces, it was possible to have URL-rewriting without any Java class. Now on your example there is some Java code, adding programmatic need (not suitable for all people) instead of configuration (more suitable for non-programmers). Also for the sake of simplicity the programmatic way should be optional, giving finest customization. For most common use-cases, the configuration-only part as done before in pretty-faces should be enough.

So no programming needed when you have common rewrites like `/user/#{username}` will be rewritten to `/user/view.xhtml?username=#{value}`.

Or is this the case? Then maybe I over-read something and say sorry in advance for the inconveniences I may have caused.

Beside this, a wonderful library done (nearly?) right. No need to do URL-rewriting in your application anymore, very nice and fully "transparent" to your web application.

Love it. 👍 

Best regards,
Roland

**Comment by chkal** [comment]
Hi,

thanks for your feedback. Nice to hear that you like Rewrite.

However, we decided back then that a programmatic configuration API would be  superior compared to XML files. Coding your configuration gives you much more flexibility you won't ever get from XML.

I don't fully understand your "XML is better for non-programmers" argument. Why should a non-programmer edit these mapping files? The configuration as part of the application and should only be modified by the developers.

However, one could easily build some custom XML DSL on top of the programmatic API if this is really needed. The annotations that can be used for configuring Rewrite also use the low level programmatic API.

**Comment by Quix0r** [comment]
Maybe a non-Java programmer. ;-)

**Comment by chkal** [comment]
Well, I could argue that non-programmer can read the Java DSL better than XML, because the Java DSL reads like English sentences. ;-)

However, I don't think that there will be a XML based configuration addon for Rewrite in the future. Simply because it means a lot of work and IMO brings very little benefit. But if you like the PrettyFaces way of configuration, you can simply use `rewrite-config-prettyfaces`, which basically translates the old PrettyFaces configuration to the Rewrite rule system.

**Comment by lincolnthree** [comment]
One can always write their own configuration file-driven method for Rewrite, as well. That's the beauty of having a core Java library - you can implement configuration with any method you choose. This is how we have so many extensions and integrations for other systems, even other rewrite filter configuration files. Take a look at the sources in any of the "config-*" folders for examples.

**Comment by Quix0r** [comment]
I think I come to use `Rewrite` as internationalization in URLs is what I may also look for. Thank you all for your valuable feedback!
