### ISSUE TITLE
Add a parameter to disable WEB-INF/classes scanning

### ISSUE THREAD

**Issue by kalgon** [ocpsoft/rewrite#253]
Hi,

would it be possible to have some flag to disable the scanning of WEB-INF/classes?

    <context-param>
        <param-name>org.ocpsoft.rewrite.annotation.SCAN_CLASSES_DIRECTORY</param-name>
        <param-value>false</param-value>
    </context-param>

currently, classes directory is always scanned while lib directory scanning must be enabled.

I am asking for this feature because I have a highly-modular application where my war only contains modules/jars (where each module contains all layers from persistence to presentation) and I am always getting this warning:

    WARNING [org.ocpsoft.rewrite.annotation.scan.WebClassesFinder] (default task-15) Cannot find classes folder: /WEB-INF/classes/

Thanks.

**Comment by swissclash79** [comment]
Hello

I use the awesome rewrite framework in a JSF application with JoinFaces.

A question here: Why has this issue been added to the milestone 3.4.2.Final but in fact it is not included in the release 3.4.2.Final?
As far as I can see, the related pull request has been merged [after](https://github.com/ocpsoft/rewrite/compare/3.4.2.Final...master) the release 3.4.2.Final.

Is there any chance to be able to use this improvement any time soon?

Thanks for your hard work anyway and thank you for a feedback!

**Comment by swissclash79** [comment]
> Hello
> 
> I use the awesome rewrite framework in a JSF application with JoinFaces.
> 
> A question here: Why has this issue been added to the milestone 3.4.2.Final but in fact it is not included in the release 3.4.2.Final?
> As far as I can see, the related pull request has been merged [after](https://github.com/ocpsoft/rewrite/compare/3.4.2.Final...master) the release 3.4.2.Final.
> 
> Is there any chance to be able to use this improvement any time soon?
> 
> Thanks for your hard work anyway and thank you for a feedback!

@chkal Should I open a new issue for that?

**Comment by chkal** [comment]
Looks like you are correct. This feature is definitely not part of 3.4.2.Final. But it is included 3.4.3.Final which was released earlier this month. I updated the issue milestone.
