### ISSUE TITLE
org.ocpsoft:ocpsoft-parent:pom:15 is not in Maven Central

### ISSUE THREAD

**Issue by seanf** [ocpsoft/rewrite#260]
@lincolnthree The new rewrite 3.4.2.Final release uses org.ocpsoft:ocpsoft-parent:pom:15, but this POM is not found in Maven Central.

**Comment by lincolnthree** [comment]
Hey @seanf! Thanks for the heads up. I'm not sure why that didn't go along with the release staging repository.... but... I've gone ahead and re-uploaded it. It should be available as soon as Nexus syncs with Sonatype! 

In the meantime, you can go ahead and install this:
https://github.com/ocpsoft/parent/tree/15

Sorry for the headache! Let me know if you have any other issues!
