### ISSUE TITLE
3.4.2 Not Final

### ISSUE THREAD

**Issue by matthew-a-dunlap** [ocpsoft/rewrite#261]
Quick issue, I noticed the maven listing for 3.4.2 does not have the -Final tag on it, tho the documentation lists it as so. My team is interested in updating as it has this fix https://github.com/ocpsoft/rewrite/issues/254 (thanks for that!), but are unsure whether the 3.4.2 release we are getting is fully vetted.

Thanks much :)

**Comment by matthew-a-dunlap** [comment]
Nevermind, it looks as if a full refresh of my maven archive solved the issue!

**Comment by lincolnthree** [comment]
Glad you got this sorted out! Thanks for updating :)
