### ISSUE TITLE
Problem with | character in request parameters

### ISSUE THREAD

**Issue by sinhkej** [ocpsoft/rewrite#263]
## When I activate rewrite then I have the following error when trying to pass a request parameter with | character:
`2018-05-04T10:30:39.760+0700|Severe: Error Rendering View[/view/searchResult/SearchResultTop.xhtml]
java.lang.IllegalArgumentException: [/c1s-web-userweb/view/searchResult/SearchResultTop?dispPartIds=INTE-0022162|INTE-0024495|NTE-0024496|INTE-0024497|INTE-0024498&dispAllFlg=true&searchType=10] is not a valid URL fragment. Consider encoding relevant portions of the URL with [class org.ocpsoft.urlbuilder.util.Encoder], or use the provided builder pattern via this class to specify part encoding.`
	`at org.ocpsoft.urlbuilder.AddressBuilder.create(AddressBuilder.java:107)`
	`at org.ocpsoft.rewrite.servlet.impl.HttpRewriteWrappedResponse.encodeURL(HttpRewriteWrappedResponse.java:392)`
	`at com.sun.faces.context.ExternalContextImpl.encodeActionURL(ExternalContextImpl.java:605)`
	`at javax.faces.context.ExternalContextWrapper.encodeActionURL(ExternalContextWrapper.java:108)`
	`at javax.faces.context.ExternalContextWrapper.encodeActionURL(ExternalContextWrapper.java:108)`
	`at com.sun.faces.renderkit.html_basic.FormRenderer.getActionStr(FormRenderer.java:253)`
	`at com.sun.faces.renderkit.html_basic.FormRenderer.encodeBegin(FormRenderer.java:143)`
	`at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:865)`
	`at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1854)`
	`at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)`
	`at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)`
	`at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:458)`
	`at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)`
	`at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196)`
	`at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)`
	`at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)`
	`at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121)`
	`at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)`
	`at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)`
.....................................................................................................................................................................................................
`Caused by: java.net.URISyntaxException: Illegal character in query at index 75: /c1s-web-userweb/view/searchResult/SearchResultTop?dispPartIds=INTE-0022162|INTE-0024495|NTE-0024496|INTE-0024497|INTE-0024498&dispAllFlg=true&searchType=10`
	`at java.net.URI$Parser.fail(URI.java:2848)`
	`at java.net.URI$Parser.checkChars(URI.java:3021)`
	`at java.net.URI$Parser.parseHierarchical(URI.java:3111)`
	`at java.net.URI$Parser.parse(URI.java:3063)`
	`at java.net.URI.<init>(URI.java:588)`
	`at org.ocpsoft.urlbuilder.AddressBuilder.create(AddressBuilder.java:96)`
	`... 74 more`

**Any idea?
I’m using version 3.4.1.Final of Rewrite:**
`<dependency>`
  ` <groupId>org.ocpsoft.rewrite</groupId>`
  ` <artifactId>rewrite-servlet</artifactId>`
  ` <version>3.4.1.Final</version>`
`</dependency>`

`<dependency>`
  `<groupId>org.ocpsoft.rewrite</groupId>`
   `<artifactId>rewrite-integration-faces</artifactId>`
  `<version>3.4.1.Final</version>`
`</dependency>`

`<dependency>`
 ` <groupId>org.ocpsoft.rewrite</groupId>`
  `<artifactId>rewrite-integration-cdi</artifactId>`
  `<version>3.4.1.Final</version>`
`</dependency>`

Thanks!

**Comment by chkal** [comment]
Could you please update to `3.4.2.Final` and check if this issue still occurs?

**Comment by sinhkej** [comment]
Awesome!
Rewrite version 3.4.2.Final working for me. Thanks a lot.

**Comment by chkal** [comment]
Thanks for letting us know!
