### ISSUE TITLE
Same url diferente java type

### ISSUE THREAD

**Issue by svrolanski** [ocpsoft/rewrite#266]
I want to do this:

```
@URLMappings(mappings = {
	@URLMapping(id = "Mapping1", pattern = "/shop/#{bean.id}", viewId = "/shop.xhtml"),
	@URLMapping(id = "Mapping2", pattern = "/shop/#{bean.description}", viewId = "/shop.xhtml")
})
```
But I get this "java.lang.NumberFormatException", I guess I can work around always using a string and doing the conversion myself, but I don't think prettyfaces should throw exception until all mappings are tested.

**Comment by chkal** [comment]
You should be able to use custom regex patterns to do this:

http://www.ocpsoft.org/docs/prettyfaces/3.3.3/en-US/html/Configuration.html#config.pathparams.regex

**Comment by svrolanski** [comment]
I don't think it will work, the regex seems to work for something like '/something/anotherThing/' and I want '/shop/<number OR text here>', that would be the item ID or its name. So I did like this:

```
@URLMapping(id = "Mapping", pattern = "/shop/#{bean.item}", viewId = "/shop.xhtml")
```
```
private String item; // getter and setter omit for simplicity
...
try {
  myItem = getItemById(Integer.parseInt(item));
} catch (NumberFormatException ignored) {
  myItem = getItemByDescription(item);
}
...
```

**Comment by chkal** [comment]
You could use a regex to restrict the mapping in a way, that it will only match for numeric path params. Anyway, your solution will of course also work.
