### ISSUE TITLE
java.lang.IllegalStateException: Committed

### ISSUE THREAD

**Issue by chkal** [ocpsoft/rewrite#30]
Hey Lincoln,

I'm opening a ticket for this because I think I know why this is happening. Actually it's a Rewrite bug. I'm trying to explain this in the following paragraphs.

First of all. This is the exception:

```
java.lang.IllegalStateException: Committed
    at org.eclipse.jetty.server.Response.resetBuffer(Response.java:1066)
    at org.eclipse.jetty.server.Response.sendError(Response.java:274)
    at org.eclipse.jetty.server.Response.sendError(Response.java:376)
    at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:162)
    at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:472)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
        [...]
    at java.lang.Thread.run(Thread.java:662)
```

You can reproduce it by running the `ExpressionLanguageTest` in the JSF module. This test contains a simple configuration which simply forwards `/name/{param}` to `/faces/expression-language.xhtml`. I think I know what is going wrong here:

The request to `/name/christian` comes in and is processed by the `RewriteFilter`. The flow is set to `Flow.FORWARD` and the request is then forwarded to `/faces/expression-language.xhtml`. The forwarded request hits the `RewriteFilter` a second time and it seems like it is correctly processed there.

The problem occurs inside the JSF lifecycle. At some time the `RewritePhaseListener` kicks in to process `PhaseOperations`. At this point the following code is executed:

```
Lifecycle.proceed().perform(operation.getEvent(), operation.getContext());
```

Actually I'm not 100% sure what this codes does and why. But it sets the flow to `PROCEED`. The problems seems to be that the flow of the outer request (the original request) is modified and not the flow of the forwarded one.

Later the `RewriteFilter` of the outer request continues its work after the `RequestDispatcher.forward()` call finished. Now as the flow changed from `FORWARD` to `PROCEED`, it calls `chain.doFilter()` and the request is further processed by the servlet engine. As the URL doesn't match any servlet mapping the default servlet processes it. But the default servlet won't find any resource matching the URL and therefore tries to send a 404. But this fails as the forwarded request was already committed.

So I think this is the problem. This was really difficult to debug. I thought it would be better to open a ticket for this to hear your thought about this. :)

**Comment by josivan** [comment]
I'm facing the same problem
I'm using 
rewrite 2.0.10
PrimeFaces 4.0
Mojarra 2.2.0-m12
PrimeFaces Extensions 1.2.1
Rewrite 2.0.10.Final 

Under tomcat everything works fine. But under Jetty 9. I have the same exception on console.
I still didn't find a solution for my scenario.

Do you have some suggestion?

Regards

**Comment by chkal** [comment]
Could you try to update to the latest Rewrite version and check if the problem still occurs?

**Comment by josivan** [comment]
Hello
I have updated to version 2.0.12.Final and I have the same problem.

I forgot to metion. I'm using jetty Version: 9.2.3.v20140905 and spring 4.1.6.

Regards

**Comment by chkal** [comment]
@josivan:

Could you please open a forum topic for this and include the full stacktrace and your configuration?

http://www.ocpsoft.org/support/

**Comment by josivan** [comment]
I'm working as consultant on a legacy code. I'm trying to remove prettyfaces to use rewrite. Let me try this approach first
.
I have noticed that code has dependencies of PrettyContext and I'm not finding a parallel of it on rewrite. Do we have some relationship in rewrite? Sorry for my basic question, but I'm newbie in prettyfaces/rewrite.

Thanks

Josivan

**Comment by josivan** [comment]
**@chkal:**
 
I fixed the problem updating the namespace of pretty-config.xml.

I have replaced 
```xml
<pretty-config 
    xmlns="http://ocpsoft.org/schema/rewrite-config-prettyfaces" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://ocpsoft.org/schema/rewrite-config-prettyfaces http://ocpsoft.org/xml/ns/prettyfaces/rewrite-config-prettyfaces.xsd">
```
with
```xml
<pretty-config 
  xmlns="http://ocpsoft.com/prettyfaces/3.3.3"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="
    http://ocpsoft.com/prettyfaces/3.3.3
    http://ocpsoft.com/xml/ns/prettyfaces/ocpsoft-pretty-faces-3.3.3.xsd">
```
Now it is working fine.

Thanks

Josivan

**Comment by chkal** [comment]
Great that you fixed your problem. However, I doubt that an incorrect namespace has caused this. Actually I think that Apache Digester (which we use here) is ignoring XML namespace.

**Comment by josivan** [comment]
Its possible.

I'm sure that I followed the steps as described here (http://www.ocpsoft.org/docs/prettyfaces/3.3.3/en-US/html/).
And during that I noticed the difference of namespace.

Thanks again

Josivan
