### ISSUE TITLE
Website migration - use rewrite to prevent 404 on old broken links

### ISSUE THREAD

**Issue by djmj** [ocpsoft/rewrite#305]
When some of our clients move their webseite to our system many of their old links in google are broken and its not comfortable defining rewrite rules in apache client.

Is it possible to create rewrite rules just to redirect to a different URL? 
Basically a fallback for 404 pages since those old links would not work anymore. I tried to post in forum but its locked due to the spam.

**Example:**

Old URL from old website: _/product/coca-cola-bottle.html_
New URL from our JSF rewritten website: _/p/coca-cola-1-l/1000_ 

We would save those old/new redirects in our database and load them in the rewrite config.

Is this possible?

    .addRule()
    .when(Path.matches("/product/coca-cola-bottle.html")) // page does not exists
    .perform(Redirect.to("/p/coca-cola-1-l/1000")) // 301 redirect to existing page

**Comment by lincolnthree** [comment]
Hello, yes :) StackOverflow is probably the best place to ask general questions. But here you go!

https://github.com/ocpsoft/rewrite/blob/master/config-servlet/src/main/java/org/ocpsoft/rewrite/servlet/config/Redirect.java#L103

Let me know if that helps?

**Comment by djmj** [comment]
Hello, yes did not thought about posting at SO.

I will test this but looks promising!

**Comment by djmj** [comment]
How can i do this dynamically, since i dont want to load all mappings at server start into the config. Here the SO question. Not sure if rewrite is the best option here.

https://stackoverflow.com/questions/70100287/jsf-url-migration-intercept-and-redirect-404-page-not-found-error
