### ISSUE TITLE
Problem with file upload

### ISSUE THREAD

**Issue by BorisYellnikov** [ocpsoft/rewrite#366]
I use JakartFaces 4, Tomcat 10, Weld and Rewrite for jakarta ee 10.  In this configuration h:inputFile and PrimeFaces p:fileUpload not works. When i deactivate Rewrite it works. No errors, no warnigs. Bean method to handle file upload is not called.

**Comment by lincolnthree** [comment]
Thanks for the update @BorisYellnikov - Sorry for the delay in responding.

**Comment by agoriwmt** [comment]
For those who can't switch the flag on or are using a different container, can you explain why Rewrite is triggering this behaviour? It seems the library is doing something that is causing the HttpServletRequest object to return empty parameters but I can't understand what. I tried to put a Servlet Filter in front of the request and if Rewrite is in the classpath, all parameters (for instance jakarta view state parameter) are already null (so even before the Rewrite filter itself).

Obviously this is only happening with multipart form/data.
