### ISSUE TITLE
Dynamically add url mapping as per tenant

### ISSUE THREAD

**Issue by anuragnz** [ocpsoft/rewrite#374]
Is it possible that url mapping done dynamically.
Every tenant has its own pages mapping. If a tenant adds to their DB it should automatically be available in mappings.
How this could be achieved?

If anyone knows then please suggest here.

**Comment by lincolnthree** [comment]
Hi @anuragnz - This would be done by accessing your database in the Rewrite Configuration, then doing a lookup on request, using the result to resolve the appropriate resources.

Here is one example that checks the local filesystem to see if a resource exists before handling the response:
https://github.com/ocpsoft/redoculous/blob/master/app/src/main/java/org/ocpsoft/redoculous/config/LocalFilesystemConfigurationProvider.java#L70

If you need to create a custom `Condition` that connects to your database, you can look at the `Filesystem` Condition as an example/starting point:

https://github.com/ocpsoft/rewrite/blob/main/api/src/main/java/org/ocpsoft/rewrite/config/Filesystem.java

If you're looking for domain or subdomain matching, you can use the `Domain` condition:
https://github.com/ocpsoft/rewrite/blob/main/config-servlet/src/main/java/org/ocpsoft/rewrite/servlet/config/Domain.java

**Comment by lincolnthree** [comment]
Closing this unless there is an additional issue. Thanks for your question.
